# Generated by Django 4.1.6 on 2023-03-09 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.group'),
        ),
    ]
