# Generated by Django 4.1.6 on 2023-03-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_todo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('I', 'IN PROGRESS'), ('S', 'STUCK'), ('C', 'COMPLETED')], default='I', max_length=1),
        ),
    ]
