# Generated by Django 4.1.6 on 2023-03-10 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_todo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('I', 'IN PROGRESS'), ('S', 'STUCK'), ('C', 'COMPLETED')], default='I', max_length=1)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.group')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
