# Generated by Django 4.1.6 on 2023-03-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_task_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'I'), ('STUCK', 'S'), ('COMPLETED', 'C')], default='IN PROGRESS', max_length=20),
        ),
    ]
