# Generated by Django 4.1.6 on 2023-03-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_groupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='key',
        ),
    ]
